kind: Cluster
apiVersion: postgresql.cnpg.io/v1
metadata:
  name: postgres
  namespace: shiori
spec:
  enableSuperuserAccess: false
  instances: 2
  bootstrap:
    initdb:
      database: shiori
      owner: shiori
      secret:
        name: shiori
  storage:
    size: 2Gi
  monitoring:
    enablePodMonitor: true
