apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shiori
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: demo/go-shiori
    repoURL: https://github.com/christophenne/shiori
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
