apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shiori-data
  namespace: shiori
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
